-- MySQL Script generated by MySQL Workbench
-- Thu Feb 11 22:42:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema titulacion_mecanica_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema titulacion_mecanica_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `titulacion_mecanica_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `titulacion_mecanica_db` ;

-- -----------------------------------------------------
-- Table `titulacion_mecanica_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulacion_mecanica_db`.`roles` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `slug` VARCHAR(50) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `roles_nombre_unique` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `titulacion_mecanica_db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulacion_mecanica_db`.`usuarios` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `roles_id` BIGINT(20) UNSIGNED NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `fecha_caducidad` TIMESTAMP NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuarios_email_unique` (`email` ASC) VISIBLE,
  INDEX `fk_usuario_roles` (`roles_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_roles`
    FOREIGN KEY (`roles_id`)
    REFERENCES `titulacion_mecanica_db`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `titulacion_mecanica_db`.`docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulacion_mecanica_db`.`docentes` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT(20) UNSIGNED NOT NULL,
  `identificacion_docente` VARCHAR(10) NOT NULL,
  `nombre_docente` VARCHAR(100) NOT NULL,
  `apellido_docente` VARCHAR(100) NOT NULL,
  `correo_docente` VARCHAR(100) NOT NULL,
  `celular` VARCHAR(10) NOT NULL,
  `habilitado` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `docentes_identificacion_docente_unique` (`identificacion_docente` ASC) VISIBLE,
  UNIQUE INDEX `docentes_correo_docente_unique` (`correo_docente` ASC) VISIBLE,
  UNIQUE INDEX `docentes_celular_unique` (`celular` ASC) VISIBLE,
  INDEX `fk_docentes_usuarios` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_docentes_usuarios`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `titulacion_mecanica_db`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `titulacion_mecanica_db`.`estado_temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulacion_mecanica_db`.`estado_temas` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `estado_tema` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `titulacion_mecanica_db`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulacion_mecanica_db`.`estudiantes` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT(20) UNSIGNED NOT NULL,
  `indentificacion_estudiante` VARCHAR(10) NOT NULL,
  `nombre_estudiante` VARCHAR(100) NOT NULL,
  `apellido_estudiante` VARCHAR(100) NOT NULL,
  `correo_estudiante` VARCHAR(255) NOT NULL,
  `celular_estudiante` VARCHAR(10) NOT NULL,
  `periodo` CHAR(4) NOT NULL,
  `egresado` TINYINT(1) NULL DEFAULT NULL,
  `graduado` TINYINT(1) NULL DEFAULT NULL,
  `rechazado` TINYINT(1) NULL DEFAULT NULL,
  `observaciones` TEXT NOT NULL,
  `condiciones` TEXT NOT NULL,
  `habilitado` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `estudiantes_indentificacion_estudiante_unique` (`indentificacion_estudiante` ASC) VISIBLE,
  UNIQUE INDEX `estudiantes_correo_estudiante_unique` (`correo_estudiante` ASC) VISIBLE,
  UNIQUE INDEX `estudiantes_celular_estudiante_unique` (`celular_estudiante` ASC) VISIBLE,
  INDEX `fk_estudiante_usuario` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `titulacion_mecanica_db`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `titulacion_mecanica_db`.`tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulacion_mecanica_db`.`tipos` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_tema` VARCHAR(150) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `titulacion_mecanica_db`.`temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulacion_mecanica_db`.`temas` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `docentes_id` BIGINT(20) UNSIGNED NOT NULL,
  `tipos_id` BIGINT(20) UNSIGNED NOT NULL,
  `titulo` VARCHAR(150) NOT NULL,
  `decripcion` TEXT NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  `habilitado` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `temas_titulo_unique` (`titulo` ASC) VISIBLE,
  INDEX `fk_docentes_temas` (`docentes_id` ASC) VISIBLE,
  INDEX `fk_tipos_temas` (`tipos_id` ASC) VISIBLE,
  CONSTRAINT `fk_docentes_temas`
    FOREIGN KEY (`docentes_id`)
    REFERENCES `titulacion_mecanica_db`.`docentes` (`id`),
  CONSTRAINT `fk_tipos_temas`
    FOREIGN KEY (`tipos_id`)
    REFERENCES `titulacion_mecanica_db`.`tipos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `titulacion_mecanica_db`.`estudiantes_temas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulacion_mecanica_db`.`estudiantes_temas` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `estudiantes_id` BIGINT(20) UNSIGNED NOT NULL,
  `temas_id` BIGINT(20) UNSIGNED NOT NULL,
  `docentes_id` BIGINT(20) UNSIGNED NOT NULL,
  `estado_tema_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estudiante_temas` (`estudiantes_id` ASC) VISIBLE,
  INDEX `fk_temas_estudiantes` (`temas_id` ASC) VISIBLE,
  INDEX `fk_temas_docentes` (`docentes_id` ASC) VISIBLE,
  INDEX `fk_temas_estado` (`estado_tema_id` ASC) VISIBLE,
  CONSTRAINT `fk_estudiante_temas`
    FOREIGN KEY (`estudiantes_id`)
    REFERENCES `titulacion_mecanica_db`.`estudiantes` (`id`),
  CONSTRAINT `fk_temas_docentes`
    FOREIGN KEY (`docentes_id`)
    REFERENCES `titulacion_mecanica_db`.`docentes` (`id`),
  CONSTRAINT `fk_temas_estado`
    FOREIGN KEY (`estado_tema_id`)
    REFERENCES `titulacion_mecanica_db`.`estado_temas` (`id`),
  CONSTRAINT `fk_temas_estudiantes`
    FOREIGN KEY (`temas_id`)
    REFERENCES `titulacion_mecanica_db`.`temas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `titulacion_mecanica_db`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulacion_mecanica_db`.`failed_jobs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `titulacion_mecanica_db`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulacion_mecanica_db`.`menus` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(150) NOT NULL,
  `menu_nombre` VARCHAR(150) NOT NULL,
  `icono` VARCHAR(150) NOT NULL,
  `url` VARCHAR(150) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `menus_menu_nombre_unique` (`menu_nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `titulacion_mecanica_db`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulacion_mecanica_db`.`migrations` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `titulacion_mecanica_db`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulacion_mecanica_db`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  INDEX `password_resets_email_index` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `titulacion_mecanica_db`.`rompimiento_docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulacion_mecanica_db`.`rompimiento_docente` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `docentes_id` BIGINT(20) UNSIGNED NOT NULL,
  `estudiante_temas_id` BIGINT(20) UNSIGNED NOT NULL,
  `motivo` TEXT NOT NULL,
  `observaciones` TEXT NOT NULL,
  `recomendaciones` TEXT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rompimiento_docente` (`docentes_id` ASC) VISIBLE,
  INDEX `fk_rompimiento_temas_d` (`estudiante_temas_id` ASC) VISIBLE,
  CONSTRAINT `fk_rompimiento_docente`
    FOREIGN KEY (`docentes_id`)
    REFERENCES `titulacion_mecanica_db`.`docentes` (`id`),
  CONSTRAINT `fk_rompimiento_temas_d`
    FOREIGN KEY (`estudiante_temas_id`)
    REFERENCES `titulacion_mecanica_db`.`estudiantes_temas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `titulacion_mecanica_db`.`rompimiento_estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulacion_mecanica_db`.`rompimiento_estudiante` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `estudiantes_id` BIGINT(20) UNSIGNED NOT NULL,
  `estudiante_temas_id` BIGINT(20) UNSIGNED NOT NULL,
  `motivo` TEXT NOT NULL,
  `observaciones` TEXT NOT NULL,
  `recomendaciones` TEXT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rompimiento_estudiantes` (`estudiantes_id` ASC) VISIBLE,
  INDEX `fk_rompimiento_temas_e` (`estudiante_temas_id` ASC) VISIBLE,
  CONSTRAINT `fk_rompimiento_estudiantes`
    FOREIGN KEY (`estudiantes_id`)
    REFERENCES `titulacion_mecanica_db`.`estudiantes` (`id`),
  CONSTRAINT `fk_rompimiento_temas_e`
    FOREIGN KEY (`estudiante_temas_id`)
    REFERENCES `titulacion_mecanica_db`.`estudiantes_temas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `titulacion_mecanica_db`.`sub_menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulacion_mecanica_db`.`sub_menus` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `menus_id` BIGINT(20) UNSIGNED NOT NULL,
  `descripcion` VARCHAR(150) NOT NULL,
  `sub_menu_nombre` VARCHAR(150) NOT NULL,
  `icono` VARCHAR(150) NOT NULL,
  `url` VARCHAR(150) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sub_menus_sub_menu_nombre_unique` (`sub_menu_nombre` ASC) VISIBLE,
  UNIQUE INDEX `sub_menus_url_unique` (`url` ASC) VISIBLE,
  INDEX `fk_sub_menu_menu` (`menus_id` ASC) VISIBLE,
  CONSTRAINT `fk_sub_menu_menu`
    FOREIGN KEY (`menus_id`)
    REFERENCES `titulacion_mecanica_db`.`menus` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


-- -----------------------------------------------------
-- Table `titulacion_mecanica_db`.`sub_menus_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulacion_mecanica_db`.`sub_menus_roles` (
  `sub_menus_id` BIGINT(20) UNSIGNED NOT NULL,
  `roles_id` BIGINT(20) UNSIGNED NOT NULL,
  INDEX `fk_sub_menus_roles` (`sub_menus_id` ASC) VISIBLE,
  INDEX `fk_roles_sub_menus` (`roles_id` ASC) VISIBLE,
  CONSTRAINT `fk_roles_sub_menus`
    FOREIGN KEY (`roles_id`)
    REFERENCES `titulacion_mecanica_db`.`roles` (`id`),
  CONSTRAINT `fk_sub_menus_roles`
    FOREIGN KEY (`sub_menus_id`)
    REFERENCES `titulacion_mecanica_db`.`sub_menus` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
